# Generated by Django 5.2.3 on 2025-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_event_eventprice_organizer_event_organizer_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
